apiVersion: v1
kind: Secret
metadata:
  name: digemid-secret
type: Opaque
stringData:
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_USER: "Kevinariassistemas@gmail.com"
  SMTP_PASS: "muxmnskspkdeqnym"